/*
 * Codex — free and open-source Material You eBook reader.
 * Copyright (C) 2024-2025 BlindMint
 * SPDX-License-Identifier: GPL-3.0-only
 */

package us.blindmint.codex.ui.main

import androidx.compose.runtime.Immutable
import us.blindmint.codex.domain.dictionary.DictionarySource
import us.blindmint.codex.domain.library.display.LibraryLayout
import us.blindmint.codex.domain.library.sort.LibrarySortOrder
import us.blindmint.codex.domain.reader.BackgroundImage
import us.blindmint.codex.domain.reader.BackgroundScaleMode
import us.blindmint.codex.domain.reader.CustomFont

@Immutable
sealed class MainEvent {
    data class OnChangeLanguage(val value: String) : MainEvent()
    data class OnChangeTheme(val value: String) : MainEvent()
    data class OnChangeDarkTheme(val value: String) : MainEvent()
    data class OnChangePureDark(val value: String) : MainEvent()
    data class OnChangeThemeContrast(val value: String) : MainEvent()
    data class OnChangeFontFamily(val value: String) : MainEvent()
    data class OnAddCustomFont(val value: CustomFont) : MainEvent()
    data class OnRemoveCustomFont(val value: CustomFont) : MainEvent()
    data class OnChangeFontStyle(val value: Boolean) : MainEvent()
    data class OnChangeFontSize(val value: Int) : MainEvent()
    data class OnChangeLineHeight(val value: Int) : MainEvent()
    data class OnChangeParagraphHeight(val value: Int) : MainEvent()
    data class OnChangeParagraphIndentation(val value: Int) : MainEvent()
    data class OnChangeShowStartScreen(val value: Boolean) : MainEvent()
    data class OnChangeSidePadding(val value: Int) : MainEvent()
    data class OnChangeDoubleClickTranslation(val value: Boolean) : MainEvent()
    data class OnChangeFastColorPresetChange(val value: Boolean) : MainEvent()
    data class OnChangeBrowseLayout(val value: String) : MainEvent()
    data class OnChangeBrowseAutoGridSize(val value: Boolean) : MainEvent()
    data class OnChangeBrowseGridSize(val value: Int) : MainEvent()
    data class OnChangeBrowseGridSizeSettings(val value: Int) : MainEvent()
    data class OnChangeBrowseSortOrder(val value: String) : MainEvent()
    data class OnChangeBrowseSortOrderDescending(val value: Boolean) : MainEvent()
    data class OnChangeBrowseIncludedFilterItem(val value: String) : MainEvent()
    data class OnChangeUseCalibreOpfMetadata(val value: Boolean) : MainEvent()
    data class OnChangeTextAlignment(val value: String) : MainEvent()
    data class OnChangeDoublePressExit(val value: Boolean) : MainEvent()
    data class OnChangeLetterSpacing(val value: Int) : MainEvent()
    data class OnChangeAbsoluteDark(val value: Boolean) : MainEvent()
    data class OnChangeCutoutPadding(val value: Boolean) : MainEvent()
    data class OnChangeFullscreen(val value: Boolean) : MainEvent()
    data class OnChangeKeepScreenOn(val value: Boolean) : MainEvent()
    data class OnChangeVerticalPadding(val value: Int) : MainEvent()
    data class OnChangeHideBarsOnFastScroll(val value: Boolean) : MainEvent()
    data class OnChangePerceptionExpander(val value: Boolean) : MainEvent()
    data class OnChangePerceptionExpanderPadding(val value: Int) : MainEvent()
    data class OnChangePerceptionExpanderThickness(val value: Int) : MainEvent()
    data class OnChangeScreenOrientation(val value: String) : MainEvent()
    data class OnChangeCustomScreenBrightness(val value: Boolean) : MainEvent()
    data class OnChangeScreenBrightness(val value: Float) : MainEvent()
    data class OnChangeHorizontalGesture(val value: String) : MainEvent()
    data class OnChangeHorizontalGestureScroll(val value: Float) : MainEvent()
    data class OnChangeHorizontalGestureSensitivity(val value: Float) : MainEvent()
    data class OnChangeBottomBarPadding(val value: Int) : MainEvent()
    data class OnChangeHighlightedReading(val value: Boolean) : MainEvent()
    data class OnChangeHighlightedReadingThickness(val value: Int) : MainEvent()
    data class OnChangeChapterTitleAlignment(val value: String) : MainEvent()
    data class OnChangeImages(val value: Boolean) : MainEvent()
    data class OnChangeImagesCornersRoundness(val value: Int) : MainEvent()
    data class OnChangeImagesAlignment(val value: String) : MainEvent()
    data class OnChangeImagesWidth(val value: Float) : MainEvent()
    data class OnChangeImagesColorEffects(val value: String) : MainEvent()
    data class OnChangeProgressBar(val value: Boolean) : MainEvent()
    data class OnChangeProgressBarPadding(val value: Int) : MainEvent()
    data class OnChangeProgressBarAlignment(val value: String) : MainEvent()
    data class OnChangeProgressBarFontSize(val value: Int) : MainEvent()
    data class OnChangeBrowsePinnedPaths(val value: String) : MainEvent()
    data class OnChangeFontThickness(val value: String) : MainEvent()
    data class OnChangeProgressCount(val value: String) : MainEvent()
    data class OnChangeHorizontalGestureAlphaAnim(val value: Boolean) : MainEvent()
    data class OnChangeHorizontalGesturePullAnim(val value: Boolean) : MainEvent()
    data class OnChangeSearchHighlightColor(val value: Long) : MainEvent()
    data class OnChangeSearchScrollbarOpacity(val value: Double) : MainEvent()
    data class OnChangeShowSearchScrollbar(val value: Boolean) : MainEvent()

    // Dictionary Events
    data class OnChangeDictionarySource(val value: DictionarySource) : MainEvent()
    data class OnChangeCustomDictionaryUrl(val value: String) : MainEvent()
    data class OnChangeDoubleTapDictionary(val value: Boolean) : MainEvent()
    data class OnChangeOfflineDictionaryEnabled(val value: Boolean) : MainEvent()
    data class OnChangeOpenLookupsInApp(val value: Boolean) : MainEvent()

    // Library Events
    data class OnChangeLibraryLayout(val value: LibraryLayout) : MainEvent()
    data class OnChangeLibraryAutoGridSize(val value: Boolean) : MainEvent()
    data class OnChangeLibraryGridSize(val value: Int) : MainEvent()
    data class OnChangeLibraryGridSizeSettings(val value: Int) : MainEvent()
    data class OnChangeLibraryListSize(val value: Int) : MainEvent()
    data class OnChangeLibrarySortOrder(val value: String) : MainEvent()
    data class OnChangeLibrarySortOrderDescending(val value: Boolean) : MainEvent()
    data class OnChangeLibraryShowCategoryTabs(val value: Boolean) : MainEvent()
    data class OnChangeLibraryAlwaysShowDefaultTab(val value: Boolean) : MainEvent()
    data class OnChangeLibraryShowBookCount(val value: Boolean) : MainEvent()
    data class OnChangeLibraryTitlePosition(val value: us.blindmint.codex.domain.library.display.LibraryTitlePosition) : MainEvent()
    data class OnChangeLibraryShowReadButton(val value: Boolean) : MainEvent()
    data class OnChangeLibraryShowProgress(val value: Boolean) : MainEvent()

    // Background Image Events
    data class OnChangeBackgroundImage(val value: BackgroundImage?) : MainEvent()
    data class OnAddCustomBackgroundImage(val value: BackgroundImage) : MainEvent()
    data class OnRemoveCustomBackgroundImage(val value: BackgroundImage) : MainEvent()
    data class OnChangeBackgroundImageOpacity(val value: Float) : MainEvent()
    data class OnChangeBackgroundScaleMode(val value: BackgroundScaleMode) : MainEvent()

    // Comic Reader Events
    data class OnChangeComicReadingDirection(val value: String) : MainEvent()
    data class OnChangeComicReaderMode(val value: String) : MainEvent()
    data class OnChangeComicTapZone(val value: Int) : MainEvent()
    data class OnChangeComicInvertTaps(val value: String) : MainEvent()
    data class OnChangeComicScaleType(val value: Int) : MainEvent()
    data class OnChangeComicProgressBar(val value: Boolean) : MainEvent()
    data class OnChangeComicProgressBarPadding(val value: Int) : MainEvent()
    data class OnChangeComicProgressBarAlignment(val value: String) : MainEvent()
    data class OnChangeComicProgressBarFontSize(val value: Int) : MainEvent()
    data class OnChangeComicProgressCount(val value: String) : MainEvent()
    data class OnChangeComicBackgroundColor(val value: String) : MainEvent()

    // Speed Reader Events
    data class OnChangeSpeedReadingWpm(val value: Int) : MainEvent()
    data class OnChangeSpeedReadingManualSentencePauseEnabled(val value: Boolean) : MainEvent()
    data class OnChangeSpeedReadingSentencePauseDuration(val value: Int) : MainEvent()
    data class OnChangeSpeedReadingOsdEnabled(val value: Boolean) : MainEvent()
    data class OnChangeSpeedReadingWordSize(val value: Int) : MainEvent()
    data class OnChangeSpeedReadingAccentCharacterEnabled(val value: Boolean) : MainEvent()
    data class OnChangeSpeedReadingAccentColor(val value: Long) : MainEvent()
    data class OnChangeSpeedReadingAccentOpacity(val value: Float) : MainEvent()
    data class OnChangeSpeedReadingShowVerticalIndicators(val value: Boolean) : MainEvent()
    data class OnChangeSpeedReadingVerticalIndicatorsSize(val value: Int) : MainEvent()
    data class OnChangeSpeedReadingVerticalIndicatorType(val value: String) : MainEvent()
    data class OnChangeSpeedReadingShowHorizontalBars(val value: Boolean) : MainEvent()
    data class OnChangeSpeedReadingHorizontalBarsThickness(val value: Int) : MainEvent()
    data class OnChangeSpeedReadingHorizontalBarsLength(val value: Float) : MainEvent()
    data class OnChangeSpeedReadingHorizontalBarsDistance(val value: Int) : MainEvent()
    data class OnChangeSpeedReadingHorizontalBarsColor(val value: Long) : MainEvent()
    data class OnChangeSpeedReadingHorizontalBarsOpacity(val value: Float) : MainEvent()
    data class OnChangeSpeedReadingFocalPointPosition(val value: Float) : MainEvent()
    data class OnChangeSpeedReadingOsdHeight(val value: Float) : MainEvent()
    data class OnChangeSpeedReadingOsdSeparation(val value: Float) : MainEvent()
    data class OnChangeSpeedReadingAutoHideOsd(val value: Boolean) : MainEvent()
    data class OnChangeSpeedReadingCenterWord(val value: Boolean) : MainEvent()
    data class OnChangeSpeedReadingFocusIndicators(val value: String) : MainEvent()
    data class OnChangeSpeedReadingCustomFontEnabled(val value: Boolean) : MainEvent()
    data class OnChangeSpeedReadingSelectedFontFamily(val value: String) : MainEvent()
    data class OnChangeSpeedReadingKeepScreenOn(val value: Boolean) : MainEvent()
}